// Tabla de prefijos para determinar provincia
const provincias = [
  { nombre: "Ciudad de Buenos Aires", prefijos: ["A", "B", "C"], sufijosPortables: ["A", "B", "C"] },
  { nombre: "Buenos Aires", prefijos: ["D", "E"], sufijosPortables: ["D", "E"] },
  { nombre: "Santa Fe", prefijos: ["F"], sufijosPortables: ["F"] },
  { nombre: "Chaco", rango: ["GAA", "GOZ"] },
  { nombre: "Formosa", rango: ["GPA", "GZZ"] },
  { nombre: "Córdoba", prefijos: ["H"], sufijosPortables: ["H"] },
  { nombre: "Entre Ríos", prefijos: ["J"], sufijosPortables: ["J"] },
  { nombre: "Tucumán", prefijos: ["K"], sufijosPortables: ["K"] },
  { nombre: "Corrientes", prefijos: ["L"], sufijosPortables: ["L"] },
  { nombre: "Mendoza", prefijos: ["M"], sufijosPortables: ["M"] },
  { nombre: "Santiago del Estero", prefijos: ["N"] },
  { nombre: "Salta", prefijos: ["O"], sufijosPortables: ["O"] },
  { nombre: "San Juan", prefijos: ["P"], sufijosPortables: ["P"] },
  { nombre: "San Luis", prefijos: ["Q"], sufijosPortables: ["Q"] },
  { nombre: "Catamarca", prefijos: ["R"], sufijosPortables: ["R"] },
  { nombre: "La Rioja", prefijos: ["S"], sufijosPortables: ["S"] },
  { nombre: "Jujuy", prefijos: ["T"], sufijosPortables: ["T"] },
  { nombre: "La Pampa", prefijos: ["U"], sufijosPortables: ["U"] },
  { nombre: "Río Negro", prefijos: ["V"], sufijosPortables: ["V"] },
  { nombre: "Chubut", prefijos: ["W"], sufijosPortables: ["W"] },
  { nombre: "Santa Cruz", rango: ["XAA", "XOZ"] },
  { nombre: "Tierra del Fuego", rango: ["XPA", "XZZ"] },
  { nombre: "Misiones", prefijos: ["I"], sufijosPortables: ["I"] },
  { nombre: "Antártida e Islas del Atlántico Sur", prefijos: ["Z"], sufijosPortables: ["Z"] },
  { nombre: "Neuquén", prefijos: ["Y"], sufijosPortables: ["Y"] },
];
